# Generated by Django 4.0 on 2022-01-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(max_length=1000, null=True, verbose_name='Imagem')),
                ('link', models.CharField(max_length=1000, null=True, verbose_name='Link')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_aproximada', models.DateField(verbose_name='Data Aproximada')),
                ('CEP', models.CharField(max_length=11, null=True, verbose_name='CEP')),
                ('autor', models.CharField(max_length=200, null=True, verbose_name='Autor(deixo em branco caso autor seja desconhecido)')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitante.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, verbose_name='Código do país(E.g: BR)')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(verbose_name='Data/hora')),
                ('contato', models.CharField(max_length=300, verbose_name='Email/Telefone')),
                ('conteudo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitante.conteudo')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=200)),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitante.pais')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitante.estado'),
        ),
    ]
